Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TradingTool.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Happy Portfolio Tool.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Happy Portfolio Tool.";

            return View();
        }

        public ActionResult Support()
        {
            ViewBag.Message = "Help Us keeping running this Trading Tool.";

            return View();
        }
    }
}

Controllers/LoginController.cs
using BEANlayer;
using DAOlayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace TradingTool.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        [HttpGet]
        public ActionResult Login(string message = "")
        {
            ViewBag.Message = message;
            return View();
        }
        [HttpPost]   // Se ejecuta el Post cuando se hace accion con el BOTON  OJO----
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginBEAN plogin)
        {
            LoginBEAN loginBean = new LoginBEAN();
            loginBean = new LoginDAO().BuscarLoginByUserId(plogin);
            //         if (login.userID == "admin"  && login.userPassword == "admin" )
            if (loginBean.userID != null) 
            {
//                FormsAuthentication.SetAuthCookie(User.userID, true);
                Session["Login"] = plogin.userID;
                Session["Password"] = plogin.userPassword;
                return RedirectToAction("Index", "Portfolio"); // Method in Portfolio Controller
            }
            else 
            {
                return RedirectToAction("Login", "Login", new { message = "Invalid Login Information" }); // Method in Login  Controller
            }
        }
        
        [Authorize]
        public ActionResult Logout() {
            return RedirectToAction("Login", "Login", new { message = "" }); // Method in Login  Controller
        }
    }
}

Controllers/LoginUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BEANlayer.EFUser;

namespace TradingTool.Controllers
{
    public class LoginUsersController : Controller
    {
        private DB_TradingMarketEntities1 db = new DB_TradingMarketEntities1();

        // GET: LoginUsers
        public ActionResult Index()
        {
            return View(db.tbl_Users.ToList());
        }

        // GET: LoginUsers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Users tbl_Users = db.tbl_Users.Find(id);
            if (tbl_Users == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Users);
        }

        // GET: LoginUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoginUsers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "sequenceID,userID,userPassword,userStatus,userType,expirationDate,timeUpdated")] tbl_Users tbl_Users)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Users.Add(tbl_Users);
                db.SaveChanges();
                
                if ((string)Session["Login"] == "admin")
                {
                    return RedirectToAction("Index");
                }
                else
                {

                    Session["Login"] = tbl_Users.userID;
                    return RedirectToAction("Index", "Portfolio"  );
                }

            }
            else
            {
                return View(tbl_Users);
            }


        }

        // GET: LoginUsers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Users tbl_Users = db.tbl_Users.Find(id);
            if (tbl_Users == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Users);
        }

        // POST: LoginUsers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "sequenceID,userID,userPassword,userStatus,userType,expirationDate,timeUpdated")] tbl_Users tbl_Users)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Users).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Users);
        }

        // GET: LoginUsers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Users tbl_Users = db.tbl_Users.Find(id);
            if (tbl_Users == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Users);
        }

        // POST: LoginUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Users tbl_Users = db.tbl_Users.Find(id);
            db.tbl_Users.Remove(tbl_Users);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BEANlayer;
using DAOlayer;

namespace TradingTool.Controllers
{
    public class PortfolioController : Controller
    {
        PortfolioDAO portfDAO = new PortfolioDAO();
        // GET: Portfolio
        
        [HttpGet]
        public ActionResult Index()
        {
            PortfolioDAO portfDAO = new PortfolioDAO();
            List<PortfolioBEAN> listPorf = new List<PortfolioBEAN>();
            string sessionValue = Session["Login"].ToString();
            
            listPorf = portfDAO.portfolioComposicion(sessionValue);
            return View(listPorf);
        }
        [HttpGet]
        public ActionResult PortfolioRegister()
        {
            ExchangeDAO exchangeDspDAO= new ExchangeDAO();
            ViewData["DisplayExchange"] = exchangeDspDAO.exchangeDisplayTbl();

            ShareStatusDAO shareStatusDspDAO = new ShareStatusDAO();
            ViewData["DisplayShareStatus"] = shareStatusDspDAO.shareStatusDisplayTbl();

            FinantialMarketDAO finantialMarketDspDAO = new FinantialMarketDAO();
            ViewData["DisplayFinantialMarket"] = finantialMarketDspDAO.finantialMarketDisplayTbl();

            SourceDAO sourceDspDAO = new SourceDAO();
            ViewData["DisplaySource"] = sourceDspDAO.sourceDisplayTbl();

            SectorDAO sectorDspDAO = new SectorDAO();
            ViewData["DisplaySector"] = sectorDspDAO.sectorDisplayTbl();

            IndustryDAO industryDspDAO = new IndustryDAO();
            ViewData["DisplayIndustry"] =  industryDspDAO.industryDisplayTbl();

            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePortfolio(PortfolioBEAN portfo) 
        {
            portfo.userID = Session["Login"].ToString();
            portfo.timeUpdated = DateTime.Now;
            PortfolioDAO porfDAO = new PortfolioDAO();
            bool answer = porfDAO.PortfolioRegister(portfo);
            if (answer)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
            
        }

    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About Us";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>


    <br />
    <p>
        We are building this tool trying to have a resource that allow us to have a fast picture of our Portfolio, that allow us to make on-time decisions, we do not pretent to replace all the
        wonderful online software and tools that there are in the Trading Market, we are building this software just for entertainment propuse only and to have a support tool for
        the retail traiders.
        <br />
        <br />
        This is a Beta version of this tool, so we are accepting any kind of suggestions to get a better tool for everybody.
        <br />
        <br />
        <b>If you want to custom this tool to your needs just let us know.</b>
        <br />
        <br />
        Have a happy trading All.!
        <br />
        <br />
        <br />
        <br />
        <br />
    </p>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact US";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Happy Trading Tool<br />
    Lima, Perú<br />
    <abbr title="Phone">P:</abbr>
    +51 997.048.188 -  Only WhatsApp
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:iabaaba@gmail.com">iabaaba@gmail.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:iabaaba@gmail.com">iabaaba@gmail.com</a>
</address>
<br />
<br />
<br />
<br />
<br />

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";

    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section >


</section>

Views/Home/Support.cshtml
@{
    ViewBag.Title = "Support Us";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- <h2>@ViewBag.Title</h2> -->
<h2>@ViewBag.Message</h2>

<style>
    section.support {
        column-count: initial;
        
    }
    section.support div {
        width: 100%;
    }
</style>


<section class="support">
    <div>
        We are doing our best building this tool to support our retail traiders for FREE, please help us to keep running this website
    </div>
</section>

Views/Login/Login.cshtml
@using BEANlayer
@model LoginBEAN
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <style>
        body {
            background-color: black;
            font-size: large;
            font-weight: 900;
            font-family: 'Times New Roman', Times, serif ;
        }
        section {
            background-image: url(../../Images/ScreenShot21May14.png);
            background-size: contain;
            background-repeat: no-repeat;
            background-position: center center;
            height: 550px;

            /*      padding: 1px 1px 1px 1px; /* top right botton left*/ */
        }
        container {
            padding: 0 10px;
            margin: 0 auto;
        }
        label {
            width: 120px;
            display: inline-block;  
            color: greenyellow;
            padding-left: 600px;
            font-size: 18px;
            font-weight:900;
        }
        strong {
            width: 120px;
            display: inline-block;
            color: red;
            padding-left: 600px;
            font-size: 18px;
            font-weight: 900;
        }

        .form-button {
            padding-left: 600px;
        }
        h1 {
            margin: 0px;
            color: blue;
            text-align: center;
            font-size: 60px;        
        }
        header span {
            color: forestgreen;
        }
        container a {
            color: whitesmoke;
            padding-left: 600px;
            text-decoration:none;
        }
        div div {
            color: gray;
        }

    </style>
</head>
<body>
    @using (Html.BeginForm())

    {
        @Html.AntiForgeryToken()
        <header>
            <h1> <span>Portfolio</span> Tool</h1>`
        </header>
        <main>
            <section>
                <container>
                    <br />
                    <br />
                    @Html.ActionLink("New Users", "Create", "LoginUsers")

                    <div class="form-horizontal">

                        <div class="form-group">
                            @Html.LabelFor(model => model.userID, "User ID", htmlAttributes: new { @class = "control-label" })
                            @Html.TextBoxFor(model => model.userID, htmlAttributes: new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.userPassword, "Password", htmlAttributes: new { @class = "control-label" })
                            @Html.PasswordFor(model => model.userPassword, htmlAttributes: new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-button ">
                        <input type="submit" value="Submit" class="btn btn-success" />
                    </div>
                    testPostBack
                    <input type="hidden" id="testPostBack" name="testPostBack" value="" />
                    @if (!string.IsNullOrEmpty(ViewBag.Message))
                    {
                        <div>
                            <div>
                                <strong>Attention: </strong> @ViewBag.Message
                            </div>
                        </div>
                    }
                </container>
            </section>
        </main>
        <footer>
        </footer>
    }
</body>
</html>

Views/Login/Logout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Logout</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

Views/LoginUsers/Create.cshtml
@model BEANlayer.EFUser.tbl_Users

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create New</title>
    <style>
        body {
            background-color: black;
            font-size: large;
            font-weight: 900;
            font-family: 'Times New Roman', Times, serif;
        }

        section {
            background-image: url(../../Images/ScreenShot21May14.png);
            background-size: contain;
            background-repeat: no-repeat;
            background-position: center center;
            height: 650px;
            /*      padding: 1px 1px 1px 1px; /* top right botton left*/ */        
        }

        container {
            padding: 0 10px;
            margin: 0 auto;
        }

        label {
            width: 120px;
            display: inline-block;
            color: lawngreen;
            padding-left: 5px;
            font-size: 18px;
            font-weight: 900;
        }

        .form-button {
            padding-left: 600px;
        }

        h1 {
            margin: 0px;
            color: red;
            text-align: center;
            font-size: 60px;
        }

        h4 {
            margin: 0px;
            color: red;
            font-size: 25px;
        }

        container span {
            color: crimson;
        }

        header span {
            color: crimson;
        }

        container a {
            color: whitesmoke;
            padding-left: 600px;
        }


    </style>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <header>
            <h1><span>Portfolio</span>Tool</h1>
        </header>
        <main>
            <section>
                <container>
                    <div class="form-horizontal">
                        <h4>Create New User ID</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.userID, "User ID", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.userID, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.userID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.userPassword, "Password", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.userPassword, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.userPassword, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        @if ((string)Session["Login"] == "admin")
                        {

                            <div class="form-group">
                                @Html.LabelFor(model => model.userStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.userStatus, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.userStatus, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.userType, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.userType, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.userType, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.expirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.expirationDate, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.expirationDate, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.timeUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.timeUpdated, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.timeUpdated, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        }
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" />
                                </div>
                            </div>

                        </div>

                </container>
            </section>
        </main>
        <footer>
        </footer>
    }


    @if ((string)Session["Login"] == "admin")
    {
        <div>
            @Html.ActionLink("Back to List", "Index")        
        </div>
    }
</body>
</html>

Views/LoginUsers/Delete.cshtml
@model BEANlayer.EFUser.tbl_Users

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>tbl_Users</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.userID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.userID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.userPassword)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.userPassword)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.userStatus)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.userStatus)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.userType)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.userType)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.expirationDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.expirationDate)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.timeUpdated)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.timeUpdated)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Views/LoginUsers/Details.cshtml
@model BEANlayer.EFUser.tbl_Users

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>tbl_Users</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.userID)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.userID)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.userPassword)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.userPassword)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.userStatus)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.userStatus)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.userType)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.userType)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.expirationDate)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.expirationDate)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.timeUpdated)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.timeUpdated)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.sequenceID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Views/LoginUsers/Edit.cshtml
@model BEANlayer.EFUser.tbl_Users

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>tbl_Users</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.sequenceID)
    
            <div class="form-group">
                @Html.LabelFor(model => model.userID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.userID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.userID, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.userPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.userPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.userPassword, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.userStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.userStatus, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.userStatus, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.userType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.userType, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.userType, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.expirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.expirationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.expirationDate, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.timeUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.timeUpdated, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.timeUpdated, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Views/Portfolio/Index.cshtml
@using BEANlayer;
@model  List<PortfolioBEAN>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .myclass {
        color: #df0f2e;
        font-size: 15px;
        font-weight: 600;
    }
</style>
<h2>Portfolio Performance </h2>
<!--             Title text,        View name,          Controller name-->
@Html.ActionLink("Add to Portfolio", "PortfolioRegister", "Portfolio", new { @class = "myclass" });

<table class="table">
    <thead class="">
        <tr>
            <th >Ticker_Symbol</th>
            <th>Company</th>
            <th>Unit Cost</th>
            <th>Total Cost</th>
            <th>Shares</th>
            <th>Holding_Period  in_days</th>
            <th>Market Price</th>
            <th>Market Value</th>
            <th>Gain/Lost</th>
            <th>Return %</th>
            <th>Exchange</th>
            <th>% Portfolio</th>
        </tr>
    </thead>
    <br />
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>@item.ticker_Symbol</td>
            <td>@item.companyName</td>
            <td align="right">@Decimal.Round(item.unitCost, 2)</td>
            <td align="right">@Decimal.Round(item.totalCost, 2)</td>
            <td align="right">@item.sharesQuantity</td>
            <td align="right">@item.holdingPeriodinDays</td>
            <td align="right">@Decimal.Round(item.marketPrice, 2)</td>
            <td align="right">@Decimal.Round(item.marketValue, 2)</td>
            <td align="right">@Decimal.Round(item.gainLost, 2)</td>
            <td align="right">@Decimal.Round(@item.returned, 2)</td>
            <td align="center">@item.exchangeCode</td>
            <td align="right">@Decimal.Round(item.portfolioPercentage, 2)</td>

        </tr>
        }
    </tbody>
</table>

@if ((string)Session["Login"] == "admin")
{
<div>
    <hr />
    @Html.ActionLink("Back to Users List", "Index", "LoginUsers")
    
</div>
}